version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.30
    restart: always
    ports:
    - "44661:44661"
    environment:
      PRISMA_CONFIG: |
        port: 44661
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: postgres
            user: larry
            password: rvnote
            rawAccess: true
            port: 5432
            migrations: true
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: larry
      POSTGRES_PASSWORD: rvnote
    volumes:
      - postgres:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 20001:8080
volumes:
  postgres:

networks:
  default:
    external:
      name: multi-compose