version: 2
jobs:
  build:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: circleci/node:10.15.3 # the primary container, where your job's commands are run
    environment:
      # VUE_APP_GRAPHQL_HTTP: https://note.songlairui.cn/graphql
      # VUE_APP_GRAPHQL_WS: wss://note.songlairui.cn/graphql
    steps:
      - checkout
      - attach_workspace:
          at: ~/lary-note/fe
      - restore_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
      - run: yarn
      - save_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run: yarn build
      - add_ssh_keys:
          fingerprints:
            - '93:fe:fa:b1:d0:2c:6c:24:14:11:5a:4f:d5:9c:55:10'
      - run: echo $REMOTE_HOSTKEY >> ~/.ssh/known_hosts
      - run:
          name: trans to $REMOTE_HOSTKEY
          command: tar czf - -C ./dist . | ssh ${REMOTE_USER}@$REMOTE_HOST -p $REMOTE_PORT "tar zxf - -C $REMOTE_DIST_PATH" # ~/ary-gateway/note/www

