query MyNotes(
  $where: NoteWhereInput
  $first: Int
  $last: Int
  $skip: Int
  $after: String
  $before: String
  $orderBy: NoteOrderByInput
) {
  notesStatistics: notesConnection(where: $where) {
    aggregate {
      count
    }
  }
  notesConnection(
    where: $where
    first: $first
    last: $last
    skip: $skip
    after: $after
    before: $before
    orderBy: $orderBy
  ) {
    pageInfo {
      startCursor
      endCursor
      hasPreviousPage
      hasNextPage
    }
    edges {
      cursor
      node {
        id
        title
        content
        theme
        author {
          id
          email
          name
        }
        createdAt
        updatedAt
      }
    }
    aggregate {
      count
    }
  }
}
