subscription NewNote {
  note {
    mutation
    node {
      id
      title
      content
      createdAt
      updatedAt
      theme
      author {
        id
        email
        name
      }
    }
    updatedFields
  }
}
